name: Sync upstream with local commits

on:
  schedule:
    - cron: '0 18,0,6,12 * * *'  # 北京时间2点开始每6小时执行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # 拉取完整历史记录
          token: ${{ secrets.UPSTREAM_TOKEN }}
          persist-credentials: true

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync upstream
        run: |

          #rm -rf /tmp/github_backup  # 清理旧备份
          #cp -r .github/workflows /tmp/github_backup  # 备份当前.github/workflows

          git push origin master --force

          git remote add upstream https://github.com/LmeSzinc/AzurLaneAutoScript.git # 替换为上游仓库地址
          git fetch upstream # 拉取上游最新的提交

          #rm -rf .github/workflows  # 删除当前.github/workflows
          #mv /tmp/github_backup .github/workflows # 恢复备份的.github/workflows

          git rebase upstream/master
          git push -f origin master